### ISSUE TITLE
Jool Transfer time

### ISSUE THREAD

**Issue by rsparkyc** [merlinthered/ksp_cheat_sheets#6]
You have the transfer time to jool taking 2 years 367 days, but in my experience it's more like 2 years 249 days

**Comment by Kowgan** [comment]
Transfer time varies according to the in-game year you're doing the maneuver; for all planets. Some vary more, some less; depends on their orbits.
As stated on the chart, Flight Time was based on 10 years of **average** flight possibilities simulated on AlexMoon's Launch Window Planner, from day 1. http://alexmoon.github.io/ksp/
Since that happens, you can't put a perfect number on the chart, so it's there just for guidance purpose. The ideal approach on this is to fine-tune your travel time using the tool linked above.
